#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 <day>";
    exit 1;
fi

day2=$1
echo $day2
case $day2 in [0-9])
    day2="0$day2";
    echo $day2
esac;

filename="input${day2}.txt"
url="https://adventofcode.com/2015/day/$1/input"

echo "Getting input for day $1..."
echo "Filename: ${filename}"
echo "URL: ${url}"


wget $url --load-cookies=cookies.txt  -O $filename

