#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 <day>";
    exit 1;
fi

day2=$1
echo $day2
case $day2 in [0-9])
    day2="0$day2";
    echo $day2
esac;

filename="input${day2}.txt"
url="https://adventofcode.com/2015/day/$1/input"

echo "Getting input for day $1..."
echo "Filename: ${filename}"
echo "URL: ${url}"


wget $url --load-cookies=cookies.txt  -O $filename
# wget https://adventofcode.com/2015/day/14/input --header 'Cookie: session=53616c7465645f5fc4fb91e306f940741ef1404e04d245d5ea8486de1605a11c710dcd392d1949234140fd197aa69273edcee61c334b90d40035e79703866d91'

